// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package appdb

import (
	"database/sql"
	"time"
)

type SigningKey struct {
	ID        int64     `json:"id"`
	KeyData   string    `json:"key_data"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiresAt time.Time `json:"expires_at"`
	IsActive  bool      `json:"is_active"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Role      string       `json:"role"`
	Created   time.Time    `json:"created"`
	Updated   time.Time    `json:"updated"`
	Lastlogin sql.NullTime `json:"lastlogin"`
}
