// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package appdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSigningKey(ctx context.Context, keyData string) (SigningKey, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredKeys(ctx context.Context, days sql.NullString) error
	DeleteUser(ctx context.Context, email string) error
	GetActiveSigningKey(ctx context.Context) (SigningKey, error)
	GetAllValidSigningKeys(ctx context.Context) ([]SigningKey, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkExpiredKeysInactive(ctx context.Context) error
	UpdateSigningKeyData(ctx context.Context, arg UpdateSigningKeyDataParams) error
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
